# Change these first
owner: p-l-
repo: status

sites:
  - name: IVRE
    url: https://ivre.rocks/
  - name: Droids Corporation
    url: https://www.droids-corp.org/

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: Upptime instance for my web pages
  introMessage: Status page using Upptime for IVRE and the Droids Corporation
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
