# Change these first
owner: p-l-
repo: status

sites:
  - name: Droids Corporation
    url: https://www.droids-corp.org/
  - name: IVRE
    url: https://ivre.rocks/
  - name: Miasm
    url: https://miasm.re/
  - name: Marker Beacon
    url: https://www.markerbeacon.org/

status-website:
  # cname: status.droids-corp.org
  baseUrl: /status
  logoUrl: https://avatars.githubusercontent.com/u/14372564
  name: Status
  introTitle: Upptime instance for the Droids Corporation pages
  introMessage: Status page using Upptime for the Droids Corporation
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
